name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 23 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: ^7.0

      - name: Install Deps
        run: pnpm install --no-frozen-lockfile

      - name: Create Image
        run: pnpm run start --cookie "${{ secrets.BING_COOKIE }}"

      - name: Push New Pic
        run: |
          git config --local user.email "liruifeng1024@gmail.com"
          git config --local user.name "${{ github.actor }}"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add .
          git commit -m "generated today pic" || echo "no need to commit "
          git push || echo "no file change"
